//
// Created by babay on 22.05.2018.
//

#ifndef PROVER_MVP_ANDROID_SETTINGS_H
#define PROVER_MVP_ANDROID_SETTINGS_H

//#define RECT_DEFECT
#define DEFECT 0.2
#define DEFECT_CLIENT 0.2
#define MS_PER_SWIPE_STEP 2500
#define MS_MIN_SWYPE_STEP_TIME 200
#define PAUSE_TO_ST3 1400
#define SWYPE_SPEED 1.5

#define VECTOR_WINDOW_START 0.0025
#define VECTOR_WINDOW_END 0.008

#define TARGET_RADIUS 0.22
#define DIAGONAL_TARGET_RADIUS_MULT 1.4

#define MIN_TIME_BETWEEN_DETECTORS 50

#define QUANTUM_ALPHA 16

#define USE_PER_FRAME_SHIFT true

#define RESET_SUM_AT_SWYPE_POINT true

#define MAX_CIRCLE_DEVIATION_TIME 100

#define MASS_DETECTOR_KEEP_SEQUENCES_WITHOUT_CIRCLE false

#define MAX_DETECTED_CODES_FOR_MASS_DETECTOR 300

#define MIN_BRIGHTNESS_CLIENT  5
#define MIN_BRIGHTNESS_SERVER  3

#define MIN_CONTRAST_CLIENT 0.06
#define MIN_CONTRAST_SERVER 0.015

#endif //PROVER_MVP_ANDROID_SETTINGS_H
